# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Poetry Install

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  
jobs:
 build:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
    runs-on: ${{ matrix.os}}  
    defaults:
      run:
        working-directory: ./example-app
        shell: bash
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      uses: snok/install-poetry@v1        
    - name: Install dependencies
      run: |
        poetry install --no-root --no-interaction
    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pypoetry/virtualenvs
          ~/AppData/Local/pypoetry/Cache/virtualenvs
        key: ${{ runner.os }}-venv      
 lint:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
    runs-on: ${{ matrix.os}}  
    defaults:
      run:
        working-directory: ./example-app
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1          
      - name: Cache build venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs
            ~/AppData/Local/pypoetry/Cache/virtualenvs
          key: ${{ runner.os }}-venv
      - name: Task lint
        run: ~/.local/bin/poetry run task lint
 
 formatter:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
    runs-on: ${{ matrix.os}}  
    defaults:
      run:
        working-directory: ./example-app
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Cache build venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs
            ~/AppData/Local/pypoetry/Cache/virtualenvs
          key: ${{ runner.os }}-venv
      - name: Task Formatter
        run: ~/.local/bin/poetry run task formatter

 security:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
    runs-on: ${{ matrix.os}}  
    defaults:
      run:
        working-directory: ./example-app
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Cache build venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:          
          path: |   
            ~/.cache/pypoetry/virtualenvs
            ~/AppData/Local/pypoetry/Cache/virtualenvs
          key: ${{ runner.os }}-venv
      - name: Task Security
        run: ~/.local/bin/poetry run task security
  
 Unitests:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
    runs-on: ${{ matrix.os}}  
    defaults:
      run:
        working-directory: ./example-app
    needs: [lint, formatter, security]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Cache build venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs
            ~/AppData/Local/pypoetry/Cache/virtualenvs
          key: ${{ runner.os }}-venv
      - name: Task UniTest
        run: ~/.local/bin/poetry run task test
