# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Poetry Install

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  
concurrency:
  group: '${{ jobs.<job_id>.steps[*].name }}'
  cancel-in-progress: true
jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./example-app
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      uses: snok/install-poetry@v1      
    - name: Install dependencies
      run: |
        poetry install --no-root --no-interaction
    - name: Task Test
      run: poetry run task test
    - name: Task lint
      run: poetry run task lint
    - name: Task Formatter
      run: poetry run task formatter
    - name: Task Security
      run: poetry run task security
        
